import type { City } from "../api/getCities";

/**
 * A few dozen real rows, kept small enough that a reader can see why any
 * assertion over them holds. It carries the same quirks the committed dataset
 * does: a row recorded with no population, and rows whose ascii name differs
 * from their name.
 */
export const CITY_FIXTURE: City[] = [
  {
    id: 1392685764,
    name: "Tokyo",
    nameAscii: "Tokyo",
    country: "Japan",
    countryIso3: "JPN",
    capital: "primary",
    population: 39105000,
  },
  {
    id: 1360771077,
    name: "Jakarta",
    nameAscii: "Jakarta",
    country: "Indonesia",
    countryIso3: "IDN",
    capital: "primary",
    population: 33756000,
  },
  {
    id: 1356226629,
    name: "Mumbai",
    nameAscii: "Mumbai",
    country: "India",
    countryIso3: "IND",
    capital: "admin",
    population: 24973000,
  },
  {
    id: 1608618140,
    name: "Manila",
    nameAscii: "Manila",
    country: "Philippines",
    countryIso3: "PHL",
    capital: "primary",
    population: 24922000,
  },
  {
    id: 1156237133,
    name: "Guangzhou",
    nameAscii: "Guangzhou",
    country: "China",
    countryIso3: "CHN",
    capital: "admin",
    population: 26940000,
  },
  {
    id: 1410836482,
    name: "Seoul",
    nameAscii: "Seoul",
    country: "South Korea",
    countryIso3: "KOR",
    capital: "primary",
    population: 23016000,
  },
  {
    id: 1484247881,
    name: "Ciudad de Mexico",
    nameAscii: "Ciudad de Mexico",
    country: "Mexico",
    countryIso3: "MEX",
    capital: "primary",
    population: 21804000,
  },
  {
    id: 1840034016,
    name: "New York",
    nameAscii: "New York",
    country: "United States",
    countryIso3: "USA",
    capital: "",
    population: 18908608,
  },
  {
    id: 1076452580,
    name: "Sao Paulo",
    nameAscii: "Sao Paulo",
    country: "Brazil",
    countryIso3: "BRA",
    capital: "admin",
    population: 23086000,
  },
  {
    id: 1250015082,
    name: "Paris",
    nameAscii: "Paris",
    country: "France",
    countryIso3: "FRA",
    capital: "primary",
    population: 11060000,
  },
  {
    id: 1826645935,
    name: "London",
    nameAscii: "London",
    country: "United Kingdom",
    countryIso3: "GBR",
    capital: "primary",
    population: 11262000,
  },
  {
    id: 1643318494,
    name: "Moskva",
    nameAscii: "Moskva",
    country: "Russia",
    countryIso3: "RUS",
    capital: "primary",
    population: 17332000,
  },
  {
    id: 1818253931,
    name: "Al Qahirah",
    nameAscii: "Al Qahirah",
    country: "Egypt",
    countryIso3: "EGY",
    capital: "primary",
    population: 19787000,
  },
  {
    id: 1360771078,
    name: "Bogota",
    nameAscii: "Bogota",
    country: "Colombia",
    countryIso3: "COL",
    capital: "primary",
    population: 11344000,
  },
  {
    id: 1392003818,
    name: "Osaka",
    nameAscii: "Osaka",
    country: "Japan",
    countryIso3: "JPN",
    capital: "admin",
    population: 15490000,
  },
  {
    id: 1392472019,
    name: "Kyoto",
    nameAscii: "Kyoto",
    country: "Japan",
    countryIso3: "JPN",
    capital: "admin",
    population: 1463723,
  },
  {
    id: 1484661734,
    name: "Pajapan",
    nameAscii: "Pajapan",
    country: "Mexico",
    countryIso3: "MEX",
    capital: "minor",
    population: 3697,
  },
  {
    id: 1276451290,
    name: "Munchen",
    nameAscii: "Munchen",
    country: "Germany",
    countryIso3: "DEU",
    capital: "admin",
    population: 1512491,
  },
  {
    id: 1724616994,
    name: "Malaga",
    nameAscii: "Malaga",
    country: "Spain",
    countryIso3: "ESP",
    capital: "minor",
    population: 578460,
  },
  {
    id: 1036074917,
    name: "Sydney",
    nameAscii: "Sydney",
    country: "Australia",
    countryIso3: "AUS",
    capital: "admin",
    population: 4840600,
  },
  {
    id: 1710263877,
    name: "Cape Town",
    nameAscii: "Cape Town",
    country: "South Africa",
    countryIso3: "ZAF",
    capital: "primary",
    population: 3433441,
  },
  {
    id: 1554435911,
    name: "Auckland",
    nameAscii: "Auckland",
    country: "New Zealand",
    countryIso3: "NZL",
    capital: "",
    population: 1467800,
  },
  {
    id: 1887433410,
    name: "Amran",
    nameAscii: "`Amran",
    country: "Yemen",
    countryIso3: "YEM",
    capital: "admin",
    population: 0,
  },
  {
    id: 1512077267,
    name: "Ibri",
    nameAscii: "`Ibri",
    country: "Oman",
    countryIso3: "OMN",
    capital: "admin",
    population: 0,
  },
];

/**
 * The same rows in the envelope form the committed asset uses, so a stubbed
 * response reaches the same parse boundary the real download does.
 */
export const CITY_FIXTURE_ENVELOPE = {
  version: "1.91.3+r1",
  columns: [
    "id",
    "name",
    "nameAscii",
    "country",
    "countryIso3",
    "capital",
    "population",
  ],
  rows: CITY_FIXTURE.map((city) => [
    city.id,
    city.name,
    city.nameAscii,
    city.country,
    city.countryIso3,
    city.capital,
    city.population,
  ]),
};
