import type { Film } from "../api/getFilms";

/**
 * A few dozen real rows, kept small enough that a reader can see why any
 * assertion over them holds. It carries the quirks the committed dataset does:
 * the earliest and the latest year in the asset, a row with no year, rows with
 * no runtime, a fractional runtime, rows whose multi-valued properties came
 * back empty, and titles whose collation order differs from their code-unit
 * order.
 */
export const FILM_FIXTURE: Film[] = [
  {
    id: "Q595",
    title: "The Intouchables",
    year: 2011,
    runtime: 112,
    directors: ["Olivier Nakache", "Éric Toledano"],
    genres: ["drama film", "comedy film", "biographical film"],
    countries: ["France"],
  },
  {
    id: "Q1365",
    title: "Swept Away",
    year: 1974,
    runtime: 114,
    directors: ["Lina Wertmüller"],
    genres: ["drama film", "comedy film"],
    countries: ["Italy"],
  },
  {
    id: "Q2201",
    title: "Kick-Ass",
    year: 2010,
    runtime: 117,
    directors: ["Matthew Vaughn"],
    genres: ["comedy film", "action film", "superhero film", "teen film"],
    countries: ["United States", "United Kingdom"],
  },
  {
    id: "Q2345",
    title: "12 Angry Men",
    year: 1957,
    runtime: 95,
    directors: ["Sidney Lumet"],
    genres: ["drama film", "huis-clos film", "trial film"],
    countries: ["United States"],
  },
  {
    id: "Q2875",
    title: "Gone with the Wind",
    year: 1939,
    runtime: 238,
    directors: ["George Cukor", "Victor Fleming", "Sam Wood"],
    genres: [
      "drama film",
      "war film",
      "romance film",
      "melodrama",
      "historical film",
    ],
    countries: ["United States"],
  },
  {
    id: "Q3589",
    title: "The Manchurian Candidate",
    year: 2004,
    runtime: 125,
    directors: ["Jonathan Demme"],
    genres: [
      "drama film",
      "thriller film",
      "political film",
      "political thriller film",
    ],
    countries: ["United States"],
  },
  {
    id: "Q4430",
    title: "Cleopatra",
    year: 1963,
    runtime: 241,
    directors: ["Joseph L. Mankiewicz"],
    genres: [
      "drama film",
      "war film",
      "biographical film",
      "epic film",
      "sword-and-sandal film",
      "romance film",
      "historical film",
    ],
    countries: ["United States", "Switzerland", "United Kingdom"],
  },
  {
    id: "Q24871",
    title: "Avatar",
    year: 2009,
    runtime: 162,
    directors: [],
    genres: [],
    countries: [],
  },
  {
    id: "Q25188",
    title: "Inception",
    year: 2010,
    runtime: 148,
    directors: [],
    genres: [],
    countries: [],
  },
  {
    id: "Q185977",
    title: "Zeitgeist: Moving Forward",
    year: 2011,
    runtime: 161.25,
    directors: ["Peter Joseph"],
    genres: ["documentary film"],
    countries: ["United States"],
  },
  {
    id: "Q531340",
    title: "Ghajini",
    year: 2008,
    runtime: null,
    directors: ["A. R. Murugadoss"],
    genres: ["drama film", "action film", "romance film", "thriller film"],
    countries: ["India"],
  },
  {
    id: "Q541412",
    title: "13 Ghosts",
    year: 1960,
    runtime: null,
    directors: ["William Castle"],
    genres: [
      "horror film",
      "mystery film",
      "ghost film",
      "supernatural horror film",
    ],
    countries: ["United States"],
  },
  {
    id: "Q580849",
    title: "À Nous la Liberté",
    year: 1931,
    runtime: 80,
    directors: ["René Clair"],
    genres: ["comedy film", "musical film"],
    countries: ["France"],
  },
  {
    id: "Q1077309",
    title: "Él",
    year: 1953,
    runtime: 92,
    directors: ["Luis Buñuel"],
    genres: ["drama film"],
    countries: ["Mexico"],
  },
  {
    id: "Q2386718",
    title: "Defence of Sevastopol",
    year: 1911,
    runtime: 100,
    directors: ["Aleksandr Khanzhonkov", "Vasily Goncharov"],
    genres: ["silent film", "war film", "historical film"],
    countries: ["Russian Empire"],
  },
  {
    id: "Q2529345",
    title: "¡Que viva México!",
    year: 1932,
    runtime: 103,
    directors: ["Sergei Eisenstein", "Grigori Aleksandrov"],
    genres: ["drama film"],
    countries: ["Soviet Union"],
  },
  {
    id: "Q2719268",
    title: "¡Ay, Carmela!",
    year: 1990,
    runtime: 102,
    directors: ["Carlos Saura"],
    genres: ["drama film", "comedy film"],
    countries: ["Spain", "Italy"],
  },
  {
    id: "Q2919862",
    title: "Æon Flux",
    year: 2005,
    runtime: 89,
    directors: ["Karyn Kusama"],
    genres: [
      "action film",
      "science fiction film",
      "biopunk",
      "post-apocalyptic film",
      "girls with guns",
      "spy film",
      "dystopian film",
    ],
    countries: ["United States"],
  },
  {
    id: "Q106392679",
    title: "Coyote vs. Acme",
    year: 2026,
    runtime: 103,
    directors: ["Dave Green"],
    genres: [
      "fantasy film",
      "comedy film",
      "adventure film",
      "family film",
      "live-action/animated film",
    ],
    countries: ["United States"],
  },
  {
    id: "Q109860581",
    title: "Batgirl",
    year: null,
    runtime: null,
    directors: ["Adil El Arbi", "Bilall Fallah"],
    genres: ["action film", "adventure film", "crime film", "superhero film"],
    countries: ["United States"],
  },
];

/**
 * The same rows in the envelope form the committed asset uses, so a stubbed
 * response reaches the same parse boundary the real download does.
 */
export const FILM_FIXTURE_ENVELOPE = {
  version: "2026-09-04+r1",
  columns: [
    "id",
    "title",
    "year",
    "runtime",
    "directors",
    "genres",
    "countries",
  ],
  rows: FILM_FIXTURE.map((film) => [
    film.id,
    film.title,
    film.year,
    film.runtime,
    film.directors,
    film.genres,
    film.countries,
  ]),
};
